gateway:
  domain: "${app_name}.erp.dev"
  graphqlEndpoint: "https://${app_name}.erp.dev/query"
tailordb:
  namespace: "${app_name}"
  graphqlEndpoint: "https://tailordb/graphql/${app_name}"
stateflow:
  namespace: "${app_name}"
  graphqlEndpoint: "https://stateflow/graphql/${app_name}"
directory:
  graphqlEndpoint: "https://directory/graph"
pipeline:
  namespace: "${app_name}"
  graphqlEndpoint: "https://pipeline/graphql/${app_name}"
